/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,tsx}",
    "./components/**/*.{js,ts,tsx}",
    "./providers/**/*.{js,ts,tsx}",
    "./hooks/**/*.{js,ts,tsx}",
  ],

  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        display: ["Teko_500Medium"],
        "display-medium": ["Teko_500Medium"],
        "display-semibold": ["Teko_600SemiBold"],
        "display-bold": ["Teko_700Bold"],
        sans: ["Lexend_400Regular"],
        "sans-medium": ["Lexend_500Medium"],
        "sans-semibold": ["Lexend_600SemiBold"],
        "sans-bold": ["Lexend_700Bold"],
      },
      colors: {
        brand: {
          DEFAULT: "#70AC15",
          hover: "#5D8B18",
          light: "#E8F1DA",
          text: "#426808",
          dark: "#ADFF33",
          glow: "#C2FF66",
          bright: "#85CF17",
        },
        "bg-page": "#F5F7F9",
        "bg-page-dark": "#101219",
        "bg-primary": "#F9FAFB",
        "bg-primary-dark": "#181C25",
        "bg-secondary": "#EAEDF0",
        "bg-secondary-dark": "#212530",
        "bg-tertiary": "#E1E6EA",
        "bg-tertiary-dark": "#2B2F3B",
        "bg-card": "#FFFFFF",
        "bg-card-dark": "#181C25",
        "bg-hover": "#ECF3E2",
        "bg-hover-dark": "#262A36",
        "text-primary": "#191D24",
        "text-primary-dark": "#F2F5F8",
        "text-secondary": "#393F4C",
        "text-secondary-dark": "#BDC7D1",
        "text-tertiary": "#606876",
        "text-tertiary-dark": "#8F96A3",
        "text-muted": "#606876",
        "text-muted-dark": "#8F96A3",
        "text-light": "#868C98",
        "text-light-dark": "#6A7181",
        "text-inverse": "#F2F5F7",
        "text-inverse-dark": "#131620",
        border: "#D6DBE0",
        "border-strong": "#C0C7CE",
        "border-dark": "#353946",
        "border-strong-dark": "#484D5B",
        background: "#F9FAFB",
        "background-dark": "#101219",
        foreground: "#191D24",
        "foreground-dark": "#F2F5F8",
        secondary: "#EAEDF0",
        "secondary-dark": "#212530",
        "secondary-foreground": "#191D24",
        "secondary-foreground-dark": "#EBF0F4",
        muted: "#E2E6E9",
        accent: "#F0F2F5",
        "accent-foreground": "#191D24",
        destructive: "#D0253C",
        input: "#CBD1D8",
        ring: "#70AC15",
        card: "#FFFFFF",
        "card-dark": "#181C25",
        "card-foreground": "#191D24",
        "card-foreground-dark": "#F2F5F8",
        popover: "#F9FAFB",
        "popover-foreground": "#191D24",
        "muted-foreground": "#606876",
        "muted-foreground-dark": "#8F96A3",
        success: "#27A55E",
        "success-light": "#DFF6E9",
        "success-dark": "#2ED175",
        warning: "#DF8A0C",
        "warning-light": "#FCEED9",
        "warning-dark": "#F4A32A",
        error: "#D0253C",
        "error-light": "#FDE3E6",
        "error-dark": "#EB475D",
        info: "#186BBF",
        "info-light": "#D9EBFC",
        "info-dark": "#2B8CEE",
        live: "#EE382B",
        gold: "#CFA117",
        "gold-dark": "#EEBD2B",
        status: {
          live: {
            bg: "#FDE3E6",
            text: "#D0253C",
            border: "#EE382B",
          },
          active: {
            bg: "#DFF6E9",
            text: "#27A55E",
            border: "#27A55E",
          },
          pending: {
            bg: "#EAEDF0",
            text: "#606876",
            border: "#C0C7CE",
          },
          completed: {
            bg: "#ECF3E2",
            text: "#426808",
            border: "#70AC15",
          },
        },
        dark: {
          bg: "#101219",
          card: "#181C25",
          elevated: "#212530",
        },
        slate: {
          50: "#F4F7FF",
          100: "#EAF0FC",
          200: "#D6E0F2",
          300: "#B7C7E3",
          400: "#8FA3C7",
          500: "#6780A8",
          600: "#4C678E",
          700: "#384F73",
          800: "#243854",
          900: "#182842",
          950: "#0D172A",
        },
      },
    },
  },
  plugins: [],
};
