import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How ScoreForge collects, uses, and protects data across web, mobile, and display.",
};

const LAST_UPDATED = "February 19, 2026";

export default function PrivacyPolicyPage(): React.ReactNode {
  return (
    <div className="min-h-screen pb-20">
      <section className="container-narrow pt-10">
        <div className="surface-panel surface-panel-rail space-y-5 p-6 sm:p-8">
          <p className="text-caption text-muted-foreground">ScoreForge</p>
          <h1 className="text-title">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">
            This policy explains how ScoreForge handles information across the web app, mobile app,
            display app, and public API.
          </p>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
            Last updated: {LAST_UPDATED}
          </p>
          <Link href="/" className="inline-flex text-sm font-semibold text-brand editorial-link">
            Back to homepage
          </Link>
        </div>
      </section>

      <section className="container-narrow mt-6">
        <article className="surface-panel space-y-8 p-6 text-sm leading-relaxed text-muted-foreground sm:p-8">
          <section className="space-y-3">
            <h2 className="text-heading text-foreground">1. Scope</h2>
            <p>
              This policy applies to ScoreForge services, including the Next.js web application,
              Expo mobile application, Rust display application, and backend services powered by
              Convex.
            </p>
            <p>
              If your organization runs its own ScoreForge deployment, your organization is
              responsible for operating that deployment and responding to privacy requests.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">2. Information We Collect</h2>
            <div className="space-y-3">
              <p className="font-semibold text-foreground">Account and identity data</p>
              <ul className="list-inside list-disc space-y-1">
                <li>Name, email address, profile image, and authentication identifiers.</li>
                <li>Sign-in events via email/password or OAuth providers (for example, Google).</li>
                <li>Authentication session cookies or tokens used to keep you signed in.</li>
              </ul>
            </div>
            <div className="space-y-3">
              <p className="font-semibold text-foreground">Tournament and scoring data</p>
              <ul className="list-inside list-disc space-y-1">
                <li>
                  Tournament metadata, courts, participants, brackets, match states, and scoring
                  results.
                </li>
                <li>
                  Scoring audit logs, including action type, timestamp, actor (when available), and
                  score state snapshots.
                </li>
                <li>CSV exports generated by users for reports and scoring logs.</li>
              </ul>
            </div>
            <div className="space-y-3">
              <p className="font-semibold text-foreground">Security and access data</p>
              <ul className="list-inside list-disc space-y-1">
                <li>
                  API keys (stored hashed), key prefixes, key status, and last-used timestamps.
                </li>
                <li>Display pairing sessions (pairing codes, expiry, and claim status).</li>
                <li>
                  Temporary scorer credentials and sessions (PIN hashes, session token hashes,
                  expiration).
                </li>
                <li>Rate-limiting records for abuse prevention.</li>
              </ul>
            </div>
            <div className="space-y-3">
              <p className="font-semibold text-foreground">Local device storage</p>
              <ul className="list-inside list-disc space-y-1">
                <li>
                  Web app stores UI preferences in browser storage (for example, sidebar collapse
                  and onboarding dismissed state).
                </li>
                <li>
                  Mobile app stores temporary scorer session and theme preference in secure storage.
                </li>
                <li>
                  Mobile app requests camera access when you use QR scanning for scorer login.
                </li>
                <li>
                  Display app stores local config such as recent files, last Convex URL, and last
                  API key on the local machine.
                </li>
              </ul>
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">3. How We Use Information</h2>
            <ul className="list-inside list-disc space-y-1">
              <li>Authenticate users and authorize access by tournament role.</li>
              <li>Operate tournament workflows, live scoring, reporting, and score displays.</li>
              <li>Secure the platform through hashing, session controls, and rate limiting.</li>
              <li>Support operational settings like maintenance mode and registration controls.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">4. How Information Is Shared</h2>
            <ul className="list-inside list-disc space-y-1">
              <li>
                With service providers used to run the platform, including Clerk (authentication)
                and Convex (backend/data services).
              </li>
              <li>
                With users you authorize in your tournament workspace (owners, scorers, temporary
                scorers, and connected displays).
              </li>
              <li>
                Through the public API only when a valid API key is presented and authorized for the
                requested data.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">5. Retention</h2>
            <ul className="list-inside list-disc space-y-1">
              <li>
                Account and tournament data is retained until deleted by account owners, admins, or
                system workflows.
              </li>
              <li>Temporary scorer sessions expire after 24 hours.</li>
              <li>Display pairing sessions expire after 10 minutes if not completed.</li>
              <li>Expired session and rate-limit records are cleaned up on an hourly schedule.</li>
              <li>
                Account deletion in Settings removes your account and associated tournament,
                scoring, preference, and API key data handled by the application.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">6. Security</h2>
            <ul className="list-inside list-disc space-y-1">
              <li>
                API keys and temporary scorer session tokens are stored as cryptographic hashes.
              </li>
              <li>Temporary scorer PINs are hashed before storage.</li>
              <li>
                Role-based access controls restrict tournament operations to authorized users and
                scorers.
              </li>
              <li>
                The web app applies standard browser security headers including HSTS, referrer
                policy, and frame protections.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">7. Your Choices</h2>
            <ul className="list-inside list-disc space-y-1">
              <li>Update your profile in Settings.</li>
              <li>Create, rotate, revoke, and delete API keys in Settings.</li>
              <li>Delete your account from Settings to remove associated application data.</li>
              <li>
                Public deletion instructions are available at{" "}
                <Link
                  href="/account-deletion"
                  className="font-semibold text-foreground hover:text-brand"
                >
                  Account Deletion Request
                </Link>
                .
              </li>
              <li>
                Quick Bracket mode can be used without an account and is intended for in-browser
                bracket creation and printing.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">8. Contact and Requests</h2>
            <p>
              For privacy requests related to a specific ScoreForge deployment, contact the
              deployment operator or site administrator managing that instance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-heading text-foreground">9. Policy Updates</h2>
            <p>
              We may update this policy as features and data flows change. When we do, we will
              update the date at the top of this page.
            </p>
          </section>
        </article>
      </section>
    </div>
  );
}
